demo1310/config/routes.rb
Rails.application.routes.draw do
  resources :courses do
	resources :assignments
  end

  resources :users
  resources :assignments

  root "users#show_courses"

  get "signup" => "users#new"
  post "signup" => "users#create"

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  delete 'courses/:id' => 'courses#destroy'

  get 'edit' => 'users#edit'
  patch 'edit' => 'users#update'
  delete 'delete' => 'users#destroy'

  get 'assignment' => 'assignments#new'
  post 'assignment' => 'assignments#create'
  patch 'edit' => 'assignments#update'
  delete 'assignment' => 'assignments#destroy'

  get 'course_students/show_students'
  get 'course_students/add_students'
  get 'course_students/remove_students'
  get 'course_students/new_course'
  post 'course_students/create_course'

  get 'submission' => 'submissions#edit', as: 'edit_submission'
  post 'submission' => 'submissions#update'
  get 'submission/:id' => 'submissions#show', as: 'show_submission'

  get 'api/new' => 'apis#new', as: 'new_api'
  get '/auth/khan_academy/callback' => 'apis#create'

  get 'api/index'=> 'apis#index'
  
  get 'api/create'=> 'apis#create'
  

end

demo1310/app/models/submission.rb
class Submission < ActiveRecord::Base
  belongs_to :user
  belongs_to :assignment

  has_attached_file :image
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_attachment_presence :image
end

demo1310/app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController

  def edit
    @assignment = Assignment.find(params[:assignment_id])
    @submission = Submission.new
    @submission_state = params[:submission_state]
  end

  def update
    @assignment = Assignment.find(params[:assignment_id])
    @student = current_user

    @student.submissions.each do |s|
      if s.assignment.id == @assignment.id
        if params[:submission_state] && params[:submission_state] == "true"
          s.status = "Complete"
          s.save
        else
          s.status = "Incomplete"
          s.save
        end
        s.update_attributes(submission_params)
        redirect_to show_submission_path(id: s.id)
      end
    end
  end

  def show
    @submission = Submission.find(params[:id])
  end

private

  def submission_params
    params.require(:submission).permit(:status, :image, :comment)
  end

end

demo1310/app/helpers/submissions_helper.rb
module SubmissionsHelper
end

demo1310/app/views/submissions/edit.html.erb
<h1 style="font-size:25px;text-align:center">Submit Assignment</h1>

<div class="container-fluid">
  <div class="row-fluid">
    <div class="col-xs-12 col-md-4 col-md-offset-4">
      <%= form_for(@submission, :url => { :controller => "submissions", :action => "update", assignment_id: @assignment.id, submission_state: @submission_state}) do |f| %>
        <div class="form-group">
          <label for="status">Status</label>
          <br>
          <% flash.each do |key, value| %>
            <div class="alert alert-info">
              <%= value %>
            </div>

          <% end %>
          <% if @assignment.khan_exercise && !@assignment.khan_exercise.empty? %>
            <%= link_to "Connect to Khan Academy", new_api_path(assignment_id: @assignment.id),  method: "get", class: "btn btn-success" %>
          <% else %>
            <%= f.select :status, ['Complete', 'Incomplete'] %>
          <% end %>
        </div>
        <div class="form-group">
          <%= f.file_field :image %>
        </div>

        <div class="form-group">
            <label for="comment">Comment</label>
            <%= f.text_area :comment, id: "comment", :placeholder => "comment", class: "form-control" %>
          </div>

        <div class="form-group">
          <%= f.submit "Submit", class: "btn btn-primary btn-block"%>
        </div>
        <div class="form-group">
          <%= link_to 'Back', @assignment, class: "btn btn-default" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

demo1310/app/views/submissions/show.html.erb
<div class="row-fluid">
<div class="col-md-1">
</div>
<div class="col-md-4">
  <h1 style="font-size:25px"><%= @submission.assignment.name %></h1>

  
  <p><strong>Status: </strong><%= @submission.status %></p> 
  <%= image_tag @submission.image %>
  <p><strong>My comment: </strong></p><%= @submission.comment %>
  <br><br>
  <%= link_to 'Back to Assignment', assignment_path(@submission.assignment), class: "btn btn-primary" %>
  <%= link_to 'Back to Course', course_path(@submission.assignment.course), class: "btn btn-primary" %>
</div>
</div>