demo1910/config/routes.rb
Rails.application.routes.draw do
  resources :courses do
	resources :assignments
  end

  resources :assignments do
      get :autocomplete_khan_exercise_name, :on => :collection
  end

  resources :users
  resources :assignments

  root "users#show_courses"

  get "signup" => "users#new"
  post "signup" => "users#create"

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  delete 'courses/:id' => 'courses#destroy'

  get 'edit' => 'users#edit'
  patch 'edit' => 'users#update'
  delete 'delete' => 'users#destroy'

  get 'assignment' => 'assignments#new'
  post 'assignment' => 'assignments#create'
  patch 'edit' => 'assignments#update'
  delete 'assignment' => 'assignments#destroy'

  get 'course_students/show_students'
  get 'course_students/add_students'
  get 'course_students/remove_students'
  get 'course_students/new_course'
  post 'course_students/create_course'

  get 'submission' => 'submissions#edit', as: 'edit_submission'
  patch 'submission' => 'submissions#update'
  get 'submission/:id' => 'submissions#show', as: 'show_submission'

  get 'api/new' => 'apis#new', as: 'new_api'
  get '/auth/khan_academy/callback' => 'apis#create'

  get 'api/index'=> 'apis#index'

  get 'api/create'=> 'apis#create'


end

demo1910/app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :course

  has_many :submissions
  has_many :user, through: :submissions

  has_attached_file :image
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  validates_presence_of :name
end

demo1910/app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  autocomplete :khan_exercise, :name, full: true

  before_action :require_user, only: [:index, :new, :edit, :show, :update, :create, :update, :destroy]
  before_action :require_teacher, only: [:new, :create, :edit, :update, :destroy]

  def index
    if params[:course_id]
      @course = Course.find(params[:course_id])
      @assignments = @course.assignments
    else
      redirect_to root_path
    end
  end

  def new
    @assignment = Assignment.new
    @course = Course.find(params[:course_id])
    @type = params[:assign_type]
  end

  def edit
    @assignment = Assignment.find(params[:id])
  end

  def show
    @assignment = Assignment.find(params[:id])
    @course = @assignment.course
  end

  def create
    type = params[:assign_type]
    @course = Course.find(params[:course_id])
    students = @course.users.where("role = 'Student'")

    @assignment = Assignment.new(assignment_params)

    khan_exercise = nil
    if type == "khan"
      khan = JSON.parse(File.read("#{Rails.root}/public/khan-exercises.json"))
      khan.each do |k|
        khan_exercise = k if k["display_name"] == @assignment.khan_exercise
      end
      @assignment.name = khan_exercise["pretty_display_name"]
      @assignment.khan_exercise = khan_exercise["ka_url"]
      @assignment.description = khan_exercise["description"]
    end

    if @assignment.save
      students.each do |s|
        s.submissions.create(assignment: @assignment, status: "Not Yet Started", image: nil)
      end
      @course.assignments << @assignment
      redirect_to @assignment
    else
      render 'new', course_id: @course.id, assign_type: type
    end
  end

  def update
    @assignment = Assignment.find(params[:id])
    @assignment.submissions.update_all("status = 'Not Yet Started'")

    if @assignment.khan_exercise
      khan_exercise = nil
      khan = JSON.parse(File.read("#{Rails.root}/public/khan-exercises.json"))
      khan.each do |k|
        khan_exercise = k if k["display_name"] == assignment_params[:khan_exercise]
      end
      @assignment.name = khan_exercise["pretty_display_name"]
      @assignment.save
      @assignment.khan_exercise = khan_exercise["ka_url"]
      @assignment.save
      @assignment.description = khan_exercise["description"]
      @assignment.save
      @assignment.due_date = assignment_params[:due_date]
      @assignment.save
      @assignment.image = assignment_params[:image]
      if @assignment.save
        flash[:success] = "Successfully updated assignment."
      end
    else
      if @assignment.update(assignment_params)
        flash[:success] = "Successfully updated assignment."
      end
    end

    redirect_to @assignment
  end

  def destroy
    @assignment = Assignment.find(params[:id])
    @course = @assignment.course
    @assignment.destroy
    redirect_to @course
  end

  private
  def assignment_params
    params.require(:assignment).permit(:name, :khan_exercise, :description, :due_date, :image)
  end

end

demo1910/app/helpers/assignments_helper.rb
module AssignmentsHelper
end

demo1910/app/views/assignments/edit.html.erb
<h1 style="font-size:25px;text-align:center">Edit <%= @assignment.name %></h1>

<div class="container-fluid">
  <div class="row-fluid">
    <div class="col-xs-12 col-md-4 col-md-offset-4">
        <%= form_for(@assignment, :validate => true, :url => {:controller => "assignments", action: "update" }) do |f| %>
        <% if !@assignment.khan_exercise %>
          <div class="form-group">
            <label for="name">Assignment Name</label>
            <%= f.text_field :name, id: "name", :placeholder => "Name", class: "form-control" %>
          </div>
          <div class="form-group">
            <label for="description">Description</label>
            <%= f.text_field :description, id: "description", :placeholder => "Description", class: "form-control" %>
          </div>
        <% end %>
        <% if @assignment.khan_exercise %>
          <div class="form-group">
            <label for="name">Choose a Khan Academy Excercise</label><br>
            <%= f.autocomplete_field :khan_exercise, autocomplete_khan_exercise_name_assignments_path %>
          </div>
        <% end %>
        <div class="form-group">
          <label for="due_date">Due Date</label>
            <div class="input-group date" id='due_date'>
            <%= f.text_field :due_date, id: "due_date", :placeholder => "Due_date", class: "form-control" %>
            <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
            </span>
            </div>
            <div class="field_with_errors"><label id="due_date_error" class="message"></label></div>
        </div>
        <div class="form-group">
          <%= f.file_field :image %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Assignment", class: "btn btn-primary btn-block" %>
        </div>
        <div class="form-group">
          <%= link_to 'Back', assignment_path(@assignment), class: "btn btn-default" %>
        </div>
      <% end %>
    </div>
  </div>
</div>


<script type="text/javascript">
  $(function () {
    $('#due_date').datetimepicker({
        format: 'LLL',
        minDate: new Date()
        });
    $('#due_date').focusout(function () {
      if ($(this).data('DateTimePicker').date() === null) {
         $('#due_date_error').text("is invalid date");
       } else {
         $('#due_date_error').text("");
       }
     });
  });
</script>

demo1910/app/views/assignments/index.html.erb
<div class="container">
  <div class="row">
    
    <h1 class="page-header">
      <%= @course.code %>: <%= @course.name %> Assignments
      <div class=" pull-right dropdown">
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
          Create Assignment
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
          <li><%= link_to 'Normal Assignment', {:controller => "assignments", :action => "new", :course_id => @course.id, :assign_type => "normal"} %></li>
          <li><%= link_to 'Khan Academy Assignment', {:controller => "assignments", :action => "new", :course_id => @course.id, :assign_type => "khan"} %></li>
        </ul>
      </div>
    </h1>

    <div class="row">
      <div class="col-lg-12">
        <div class="table-responsive">
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th>Type</th>
                <th>Assignment</th>
                <th>Due date</th>
                <th>Description</th>
                <th>View</th>
              </tr>
            </thead>

            <% @assignments.each do |assignment| %>
              <tr>
                <% if assignment.khan_exercise %>
                  <td>Khan</td>
                <% else %>
                  <td>Normal</td>
                <% end %>
                <td><%= assignment.name %></td>
                <td><%= assignment.due_date %></td>
                <td><%= assignment.description %></td>
                <td><%= link_to 'View', assignment_path(assignment) %></td>
              </tr>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

demo1910/app/views/assignments/new.html.erb
<h1 style="font-sie:25px;text-align:center"> Create Assignment</h1>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="col-xs-12 col-md-4 col-md-offset-4"> 
      <div class="form">
          <%= form_for(@assignment, :validate => true, :url => {:controller => "assignments", action: "create", course_id: @course.id, assign_type: @type}) do |f| %>
          <% if @type == "normal" %>
            <div class="form-group">
              <label for="name">Assignment Name</label>
              <%= f.text_field :name, id: "name", :placeholder => "Name", class: "form-control" %>
            </div>
            <div class="form-group">
              <label for="description">Description</label>
              <%= f.text_field :description, id: "description", :placeholder => "Description", class: "form-control" %>
            </div>
          <% end %>
          <% if @type == "khan" %>
            <div class="form-group">
              <label for="name">Choose a Khan Academy Excercise</label><br>
              <%= f.autocomplete_field :khan_exercise, autocomplete_khan_exercise_name_assignments_path %>
            </div>
          <% end %>
          <div class="form-group">
            <label for="due_date">Due Date</label>
              <div class="input-group date" id='due_date'>
              <%= f.text_field :due_date, id: "due_date", :placeholder => "Due_date", class: "form-control" %>
              <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
              </span>
              </div>
          <div class="field_with_errors"><label id="due_date_error" class="message"></label></div>
          </div>

          <div class="form-group">
          <%= f.file_field :image %>
        </div>
        
          <div class="form-group">
            <%= f.submit "Create", class: "btn btn-primary btn-block" %>
          </div>
          <div class="form-group">
            <%= link_to 'Back', assignments_path(course_id: @course.id), class: "btn btn-default" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(function () {
    $('#due_date').datetimepicker({
        format: 'LLL',
        minDate: new Date()
      });
     $('#due_date').focusout(function () {
       if ($(this).data('DateTimePicker').date() === null) {
         $('#due_date_error').text("is invalid date");
        } else {
         $('#due_date_error').text("");
        }
     });
  });
</script>

demo1910/app/views/assignments/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">
        <%= @assignment.name %>
        <div class="pull-right">
          <% if current_user.teacher? %>
            <%= link_to 'Edit', edit_assignment_path(@assignment), class: "btn btn-primary" %>
            <%= link_to 'Delete', assignment_path(@assignment), method: :delete, data: { confirm: 'Are you sure you wish to delete this assignment?' }, class: "btn btn-danger" %>
          <% elsif current_user.student? %>
            <%= link_to 'Submit', {:controller => "submissions", :action => "edit", assignment_id: @assignment.id, id: @assignment.submissions.where(user_id:current_user.id).first.id}, class: "btn btn-primary" %>
          <% end %>
        </div>
      </h1>
      <p><strong>Due: </strong><%= @assignment.due_date %></p>
      <p><strong>Description: </strong><%= @assignment.description %></p>
      <% if @assignment.khan_exercise != nil %>
        <p><strong>Link: </strong><a href="<%= @assignment.khan_exercise %>"><%= @assignment.khan_exercise %></a></p>
      <% end %>
    </div>
  </div>

  
  <div class="row">
    <div class="col-md-5">  
      <% if @assignment.image.file? %>
      <h3>Image</h3>      
        <%= image_tag @assignment.image, {:class => "img-responsive"} %>
      <% end %>
    </div>

    <% if current_user.teacher? %>
    <div class="col-md-7">
      <h3 class="text-center">Overall Completion Rate</h3>
      <% not_yet_started = false %>
      <% started = false %>
      <% complete = false %>
     <% @assignment.submissions.each do |s| %>
      <% not_yet_started = !not_yet_started if (s.status == "Not Yet Started" && !not_yet_started) %>
      <% started = !started if (s.status == "Started" && !started) %>
      <% complete = !complete if (s.status == "Complete" && !complete) %>
    <% end %>
<%= pie_chart @assignment.submissions.group(:status).count, colors: ["F2A6A7"] if not_yet_started && !started && !complete%>
    <%= pie_chart @assignment.submissions.group(:status).count, colors: ["F2A6A7", "FCF3BD"] if not_yet_started && started && !complete%>
    <%= pie_chart @assignment.submissions.group(:status).count, colors: ["C2F0BF", "F2A6A7"] if not_yet_started && !started && complete%>
    <%= pie_chart @assignment.submissions.group(:status).count, colors: ["FCF3BD"] if !not_yet_started && started && !complete%>
    <%= pie_chart @assignment.submissions.group(:status).count, colors: ["C2F0BF", "FCF3BD"] if !not_yet_started && started && complete%>
    <%= pie_chart @assignment.submissions.group(:status).count, colors: ["C2F0BF"] if !not_yet_started && !started && complete%>
    <%= pie_chart @assignment.submissions.group(:status).count, colors: ["C2F0BF", "F2A6A7", "FCF3BD"] if not_yet_started && started && complete%>
  </div>
    <% end %>
  </div>

  <% if current_user.student? %>
    <div class="row">
      <div class="col-lg-12">
        <h2 class="page-header">
          Your submission 
          <div class="pull-right"><small>Status: </strong><%= @assignment.submissions.where("user_id == #{current_user.id}").first.status %></small></div>
        </h2>
        <% if @assignment.submissions.where(user_id:current_user.id).first.image.file? %>
          <h3> Submitted Image </h3>
          <%= image_tag @assignment.submissions.where(user_id:current_user.id).first.image, {:class => "img-responsive"} %>
        <% end %>
        <p><strong>My comment: </strong></p><%= @assignment.submissions.where(user_id:current_user.id).first.comment %>
      </div>
    </div>
  <% end %>
  
  <%= link_to 'Back to ' + @course.name, course_path(@course), {:style=>"margin-top:20px", :class=>"btn btn-primary"} %>
</div>