demo1710/config/routes.rb
Rails.application.routes.draw do
  resources :courses do
	resources :assignments
  end

  resources :assignments do
      get :autocomplete_khan_exercise_name, :on => :collection
  end

  resources :users
  resources :assignments

  root "users#show_courses"

  get "signup" => "users#new"
  post "signup" => "users#create"

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  delete 'courses/:id' => 'courses#destroy'

  get 'edit' => 'users#edit'
  patch 'edit' => 'users#update'
  delete 'delete' => 'users#destroy'

  get 'assignment' => 'assignments#new'
  post 'assignment' => 'assignments#create'
  patch 'edit' => 'assignments#update'
  delete 'assignment' => 'assignments#destroy'

  get 'course_students/show_students'
  get 'course_students/add_students'
  get 'course_students/remove_students'
  get 'course_students/new_course'
  post 'course_students/create_course'

  get 'submission' => 'submissions#edit', as: 'edit_submission'
  patch 'submission' => 'submissions#update'
  get 'submission/:id' => 'submissions#show', as: 'show_submission'

  get 'api/new' => 'apis#new', as: 'new_api'
  get '/auth/khan_academy/callback' => 'apis#create'

  get 'api/index'=> 'apis#index'

  get 'api/create'=> 'apis#create'


end

demo1710/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:index, :show, :new, :edit, :destroy, :update, :create]
  before_action :require_teacher, only: [:index, :new, :edit, :destroy, :update, :create]

  def index
    @courses = Course.all
  end

  def show
    @assignments = @course.assignments
    @assignments = @assignments.sort_by{|a| a.name}
    @enrolled_students = @course.users.where("role='Student'")
    @enrolled_students = @enrolled_students.sort_by{|es| es.last_name}
  end

  def new
    @course = Course.new
  end

  def edit
  end

  def create
    @course = Course.new(course_params)

    if @course.save
      @course.course_user_joins.create(:user => current_user)
      flash[:success] = "Course was successfully created."
    end

    redirect_to @course
  end

  def update
    if @course.update(course_params)
      flash[:success] = "Course was successfully updated."
      redirect_to @course
    else
      flash[:danger] = "Course code and/or name currently exists."
      redirect_to edit_course_path
    end
  end

  def destroy
    @course.destroy
    flash[:success] = "Course was successfully destroyed."
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:code, :description, :name)
    end
end

demo1710/app/helpers/courses_helper.rb
module CoursesHelper
end

demo1710/app/views/courses/edit.html.erb
<h1 style="font-size:25px;text-align:center">Edit <%= @course.name %></h1>

<div class="container-fluid">
  <div class="row-fluid">
    <div class="col-xs-12 col-md-4 col-md-offset-4">
      <div class="form">
          <%= form_for @course, :validate => true, url: course_path(@course), method: :patch do |f| %>
          <% if @course.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@course.errors.count, "error") %></h2>
              <ul>
                 <% @course.errors.full_messages.each do |msg| %>?
                   <li><%= msg %></li>
                 <% end %>
              </ul>
            </div>
          <% end %>
          <div class="form-group">
            <label for="code">Code</label>
            <%= f.text_field :code, id: "code", :placeholder => "Code", class: "form-control" %>
          </div>
          <div class="form-group">
            <label for="name">Name</label>
            <%= f.text_field :name, id: "name", :placeholder => "Name", class: "form-control" %>
          </div>
          <div class="form-group">
            <label for="description">Description</label>
            <%= f.text_area :description, id: "description", :placeholder => "Description", class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.submit "Update", class: "btn btn-primary btn-block" %>
          </div>
        <% end %>
        <%= link_to 'Back', course_path(@course.id), class: "btn btn-default" %>
      </div>
    </div>
  </div>
</div>

demo1710/app/views/courses/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">
        My Courses
      </h1>        
    </div>
  </div>

  <div class="row">
      <div class="col-lg-12">
        <div class="table-responsive">

          <table class="table">
            <tr>
              <th>Code</th>
              <th>Name</th>
              <th>Description</th>
              <th>link</th>
            </tr>

            <% @courses.each do|course| %>
            <tr>
               <td><%= course.code %></td>
               <td><%= course.name %></td>
               <td><%= course.description %></td>
               <td><%= link_to 'info', course_path(course) %></td>
            </tr>
            <% end %>
          </table>
        </div>
      <% if current_user.teacher? %>
      <%= link_to 'New Course', new_course_path, class: "btn btn-primary btn-block" %>
      <% end %>
    </div>
  </div>
</div>

demo1710/app/views/courses/new.html.erb
<h1 style="font-size:25px;text-align:center">Create Course</h1>

<div class="container-fluid">
  <div class="row-fluid">
    <div class="col-xs-12 col-md-4 col-md-offset-4">
      <div class="form">
          <%= form_for(@course, :validate => true) do |f| %>
          <% if @course.errors.any? %>
            <div id="error_explanation">
              <h2>
                <%= pluralize(@course.errors.count, "error") %> prohibited
                this article from being saved:
              </h2>
              <ul>
                <% @course.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="form-group">
            <label for="code">Code</label>
            <%= f.text_field :code, id: "code", :placeholder => "Code", class: "form-control" %>
          </div>
          <div class="form-group">
            <label for="name">Name</label>
            <%= f.text_field :name, id: "name", :placeholder => "Name", class: "form-control" %>
          </div>
          <div class="form-group">
            <label for="description">Description</label>
            <%= f.text_area :description, id: "description", :placeholder => "Description", class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.submit "Create", class: "btn btn-primary btn-block" %>
          </div>
        <% end %>
        <%= link_to 'Back', root_path, class: "btn btn-default" %>
      </div>
    </div>
  </div>
</div>

demo1710/app/views/courses/show.html.erb
<% if current_user.teacher? %>
  <%# If the user is a teacher %>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">
          <%= @course.code %>: <%= @course.name %> 
          <div class="pull-right">
            <%= link_to 'Edit', edit_course_path(@course), class: "btn btn-primary"%>
            <%= link_to 'Delete', @course, method: :delete, data: { confirm: 'Are you sure you wish to delete this course?' }, class: "btn btn-danger" %>
          </div> 
        </h1>
        <p><strong>Description: </strong><%= @course.description %></p>
        <%= link_to 'Assignment List', {:controller => "assignments", :action => "index", :course_id => @course.id }, class: "btn btn-default" %>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-12">
        <h2 class="page-header">
          Dashboard
          <div class="pull-right">
            <%= link_to 'Enrollments',{:controller => "course_students", :action => "show_students", :course_id => @course.id}, class: "btn btn-default" %>
          </div>
        </h2>
        <div class=" table-responsive">
          <table class="table table-bordered table-hover">
            <thead>
              <tr>
                <th class="active">Students</th>
                <% @assignments.each do |a| %>
                  <th class="active"><%= link_to a.name, assignment_path(a) %></th>
                <% end %>
              </tr>
            </thead>

            <tbody>
              <% @enrolled_students.each do |user| %> 
                <tr>
                  <td class="active"><%= user.last_name+", "+user.first_name %></td>
                  <% @assignments.each do |a| %>
                    <% s = user.submissions.where("assignment_id == #{a.id}").first %>
                    <% case s.status when "Not Yet Started" %> 
                      <td class="danger"><%= link_to s.status, {:controller => "submissions", :action => "show", :id => s.id} %></td>
                    <% when "Started" %> 
                      <td class="warning"><%= link_to s.status, {:controller => "submissions", :action => "show", :id => s.id} %></td>
                    <% when "Complete" %> 
                      <td class="success"><%= link_to s.status, {:controller => "submissions", :action => "show", :id => s.id} %></td>
                    <% end %>
                  <% end %>
                </tr>
              <% end %>
              <td class="active"><b>Average</b></td>
              <% @assignments.each do |a| %>
                <% count = 0.0 %>
                <% a.submissions.each do |s| %>
                  <% if s.status == "Complete" && s.user.in?(@enrolled_students) %>
                    <% count+=1.0 %>
                  <% end %>
                <% end %>
                <% if @enrolled_students.size != 0 %>
                  <% total = (count/@enrolled_students.size*100).floor %>
                  <% case total when 100 %>
                    <td class="success"><b><%= total %>%</b></td>
                  <% when 50..99 %>
                    <td class="warning"><b><%= total %>%</b></td>
                  <% when 0..49 %>
                    <td class="danger"><b><%= total %>%</b></td>
                  <% end %>
                <% else %>
                  <td>0%</td>
                <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>      
    </div>
  </div>
  </div>
<% else %>
  <%# If the user is a student %>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">
          <%= @course.code %>: <%= @course.name %> 
        </h1>
        <p><strong>Description: </strong><%= @course.description %></p>          
      </div>
    </div>

    <div class="row">
      <div class="col-lg-12">
        <h2 class="page-header">
          Assignment List
        </h2>
        <div class="table-responsive">
          <table class="table table-striped table-hover">
            <thead>
              <th>Assignment</th>
              <th>Due date</th>
              <th>Status</th>
            </thead>
            <% @assignments.each do |a| %>
              <tr>
                <td><%= link_to a.name, {:controller => "assignments", :action => "show", :id => a.id} %></td>
                <td><%= a.due_date %></td>
                <% current_user.submissions.each do |s| %>
                  <% if s.assignment == a%>
                    <% case s.status
                    when "Not Yet Started" %> <td class="danger"><%= link_to s.status, {:controller => "submissions", :action => "edit", :id => s.id, :assignment_id => a.id} %></td>
                  <% when "Started" %> <td class="warning"><%= link_to s.status, {:controller => "submissions", :action => "edit", :id => s.id , :assignment_id => a.id} %></td>
                  <% when "Complete" %> <td class="success"><%= link_to s.status, {:controller => "assignments", :action => "show", :id => a.id} %></td>
                  <% end %>
                <% end %>
              <% end %>
              </tr>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  </div>
<% end %>